//! `docs/api.md` names the whole contract (ARCHITECTURE.md §4.9): every op, reply tag, error
//! kind, command, dev command, event and rejection appears in it as a backticked token.
//!
//! The names come from exhaustive `match`es generated by `variants!` from the same list of
//! identifiers that the check walks, so a new variant fails the build here until it is listed,
//! and once listed the test fails until the document names it. Op names and reply tags are
//! the wire names: each listed op is built and serialized, and its `op` field must equal the
//! name listed for it.

use omnis_cli::omnis_sim::api::{
    Command, DevCommand, Draft, Event, Op, OpError, Rejection, Reply, ServiceCommand,
};
use omnis_cli::omnis_sim::omnis_data::Alignment;
use std::path::PathBuf;

/// `const $list` holds the variants' names and `fn $name` is an exhaustive `match` over the
/// type built from the same identifiers: the two cannot disagree, and a variant missing from
/// the list is a compile error (`{ .. }` matches unit, tuple and struct variants alike).
macro_rules! variants {
    ($ty:ident, $list:ident, $name:ident: $($variant:ident)*) => {
        const $list: &[&str] = &[$(stringify!($variant)),*];

        fn $name(value: &$ty) -> &'static str {
            match value {
                $($ty::$variant { .. } => stringify!($variant),)*
            }
        }
    };
}

variants!(Command, COMMANDS, command_name:
    Step Turn Interact Party Encounter Combat Cast Item Service Rest Dev);

variants!(DevCommand, DEV_COMMANDS, dev_name:
    GiveItem SetHp SetSpellPoints SetGold SetFood SetXp SetScore SetCondition SetFlag Teleport
    SetMonsterHp KillStack Reconcile);

variants!(Event, EVENTS, event_name:
    Moved Blocked Reconciled SignalsDropped TimeAdvanced Visible Door Message PartyChanged
    EncounterCheck EncounterStarted Check Bribed CombatStarted Initiative RoundStarted Turn Waited
    Dodging FeatureUsed OpportunityAttack Exchanged AttackResolved Damage MonsterCast ShieldStops
    SpellCast EffectApplied EffectEnded Concentration ReactionsSwitched TacticsChanged Reaction
    Equipped Unequipped ItemMoved ItemUsed Sensed Healed Down Wounded DeathSave Condition Death
    CombatEnded ServiceEntered ServiceLeft RoomTaken FoodBought Rumor Treated Raised Bought Sold
    Banked LevelUp SpellLearned Rested HitDiceSpent RestInterrupted RestEvent Dev);

variants!(Rejection, REJECTIONS, rejection_name:
    WrongMode PartyFull Character BadOrder NotYourTurn NoSuchStack StackDead OutOfReach
    NeedsRangedWeapon NoSuchMember SameMember MemberTwice CannotAfford UnknownSpell NotCastable
    NotEnoughPoints MissingComponents WrongTarget MemberDead MemberDown NotEnough UnknownItem
    NotInStores NotCarried NotEquippable HandsFull SlotEmpty NotUsable NotUsableHere TargetDead
    ZeroCount DevOnly UnknownId OutOfRange OffMap NotOffered NothingToTreat NotDead BankShort
    RestTooSoon NoFood NoHitDice NotReady MaxLevel NoPicks NoSuchSpell NotOnList
    CantripNotLearned SpellTooHigh AlreadyKnown NoActionLeft NoBonusActionLeft ReactionOnly
    NotABonusAction NeedsPreparation NoSuchFeature NoUsesLeft WrongChoice Tactics CannotReact
    NoSuchEntry Rule);

variants!(OpError, ERROR_KINDS, error_kind:
    Rejected UnknownMap UnknownSlot TooLong TooMany HostOnly NoEncounter NoService BadRequest
    Failed);

variants!(Reply, REPLIES, reply_variant:
    Status Viewport Script Events Automap Text Written Party Rules Rule Combat Service Time Rest
    Casts Value Done);

/// The op variants, each with its wire name; the `match` is exhaustive like the others.
macro_rules! ops {
    ($($variant:ident => $wire:literal),* $(,)?) => {
        const OPS: &[(&str, &str)] = &[$((stringify!($variant), $wire)),*];

        fn op_variant(op: &Op) -> &'static str {
            match op {
                $(Op::$variant { .. } => stringify!($variant),)*
            }
        }
    };
}

ops! {
    GameStatus => "game.status", WorldQuery => "world.query", SimCommand => "sim.command",
    SimScript => "sim.script", EventsTail => "events.tail", ViewportGet => "viewport.get",
    MapText => "map.text", AutomapGet => "automap.get", SaveWrite => "save.write",
    SaveRead => "save.read", PackReload => "pack.reload", Screenshot => "screenshot",
    ScreenText => "screen.text", PartyGet => "party.get", PartyCreate => "party.create",
    CombatGet => "combat.get", ServiceGet => "service.get", RulesList => "rules.list",
    RulesGet => "rules.get", TimeClocks => "time.clocks", TimeReconcile => "time.reconcile",
    RestGet => "rest.get", CastGet => "cast.get", RulesSet => "rules.set",
}

/// One op of every kind, to read its wire name from serde.
fn every_op() -> Vec<Op> {
    let text = || String::from("x");
    vec![
        Op::GameStatus,
        Op::WorldQuery { path: text() },
        Op::SimCommand {
            command: Command::Interact,
        },
        Op::SimScript {
            commands: Vec::new(),
        },
        Op::EventsTail { count: 1 },
        Op::ViewportGet,
        Op::MapText { map: None },
        Op::AutomapGet { map: None },
        Op::SaveWrite { path: text() },
        Op::SaveRead {
            path: text(),
            force: false,
        },
        Op::PackReload,
        Op::Screenshot {
            path: None,
            target: Default::default(),
        },
        Op::ScreenText,
        Op::PartyGet,
        Op::PartyCreate {
            character: Draft {
                name: text(),
                race: text(),
                class: text(),
                background: text(),
                alignment: Alignment::ALL[0],
                scores: [10; 6],
                skills: Vec::new(),
            },
        },
        Op::CombatGet,
        Op::ServiceGet,
        Op::RulesList,
        Op::RulesGet { slot: text() },
        Op::TimeClocks,
        Op::TimeReconcile { region: text() },
        Op::RestGet,
        Op::CastGet,
        Op::RulesSet {
            slot: text(),
            source: text(),
        },
    ]
}

/// A reply variant's tag: `serde(rename_all = "snake_case")`.
fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[test]
fn the_wire_names_are_the_ones_listed() {
    let ops = every_op();
    let mut built: Vec<&str> = ops.iter().map(op_variant).collect();
    built.sort_unstable();
    let mut listed: Vec<&str> = OPS.iter().map(|(variant, _)| *variant).collect();
    listed.sort_unstable();
    assert_eq!(built, listed, "every_op builds each op once");
    for op in &ops {
        let wire = serde_json::to_value(op).unwrap();
        let (_, name) = OPS.iter().find(|(v, _)| *v == op_variant(op)).unwrap();
        assert_eq!(wire["op"], *name, "{wire}");
    }
    // One cheap value of each other kind proves the names and tags are the wire's.
    let reply = Reply::Events { events: Vec::new() };
    let wire = serde_json::to_value(&reply).unwrap();
    assert_eq!(wire["reply"], snake(reply_variant(&reply)), "{wire}");
    let error = OpError::HostOnly;
    let wire = serde_json::to_value(&error).unwrap();
    assert_eq!(wire["kind"], error_kind(&error), "{wire}");
    let command = Command::Service(ServiceCommand::Leave);
    assert_eq!(serde_json::to_value(&command).unwrap()["Service"], "Leave");
    assert_eq!(command_name(&command), "Service");
    assert_eq!(dev_name(&DevCommand::SetGold { gold: 1 }), "SetGold");
    assert_eq!(event_name(&Event::PartyChanged), "PartyChanged");
    assert_eq!(rejection_name(&Rejection::WrongMode), "WrongMode");
    assert_eq!(snake("Casts"), "casts");
}

#[test]
fn the_api_document_names_every_op_reply_error_command_event_and_rejection() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/api.md");
    let doc = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let replies: Vec<String> = REPLIES.iter().map(|r| snake(r)).collect();
    let groups: [(&str, Vec<&str>); 7] = [
        ("op", OPS.iter().map(|(_, wire)| *wire).collect()),
        ("reply tag", replies.iter().map(String::as_str).collect()),
        ("error kind", ERROR_KINDS.to_vec()),
        ("command", COMMANDS.to_vec()),
        ("dev command", DEV_COMMANDS.to_vec()),
        ("event", EVENTS.to_vec()),
        ("rejection", REJECTIONS.to_vec()),
    ];
    let missing: Vec<String> = groups
        .iter()
        .flat_map(|(kind, names)| {
            names
                .iter()
                .filter(|name| !doc.contains(&format!("`{name}`")))
                .map(move |name| format!("{kind} `{name}`"))
        })
        .collect();
    assert!(
        missing.is_empty(),
        "docs/api.md does not name {} item(s): {}",
        missing.len(),
        missing.join(", ")
    );
    // The counts the document states are the types' counts.
    for (count, what) in [
        (COMMANDS.len(), "`Command` (11 variants)"),
        (DEV_COMMANDS.len(), "`DevCommand` (13 variants"),
        (EVENTS.len(), "`Event` has 62 variants"),
        (REJECTIONS.len(), "`Rejection` (62 variants)"),
        (ERROR_KINDS.len(), "`OpError` (10 kinds)"),
        (OPS.len(), "24 ops."),
    ] {
        let stated: usize = what
            .chars()
            .filter(char::is_ascii_digit)
            .collect::<String>()
            .parse()
            .unwrap();
        assert_eq!(
            count, stated,
            "the type has {count}; the document says {what}"
        );
        assert!(
            doc.contains(what),
            "docs/api.md lost the line naming {what}"
        );
    }
}
